Exercise 2
MaKu-kodilla/AJAX-and-API_practice pull request #2
Opened 2018-04-08 12:16 UTC by MaKu-kodilla

2018-04-08 16:34 UTC, michal-bootcamp requested changes
Zwroc uwage, ze utworzyles brancha z poprzedniego zadania, a nie z mastera i sa tu zmiany z dwoch zadan - pamietaj zeby tworzyc z mastera (albo bedac na masterze, albo podajac go na koncu komendy: `git checkout -b nowy-branch master`)

2018-04-08 16:34 UTC, michal-bootcamp commented on Zadanie 12.2 Aplikacja losująca cytaty/css/style.css
> +    color:#f1f1f1;
spacja po dwukropku

2018-04-08 16:34 UTC, michal-bootcamp commented on Zadanie 12.2 Aplikacja losująca cytaty/css/style.css
> +    color:#f1f1f1;
spacja po dwukropku

2018-04-08 16:34 UTC, michal-bootcamp commented on Zadanie 12.2 Aplikacja losująca cytaty/index.html
> +                <button class="trigger"> Random quote </button>
niepotrzebne spacje wewnatrz buttona

2018-04-08 16:35 UTC, michal-bootcamp commented
poprosze zebys jeszcze ujednolicil wyglad obu buttonow na stronie (odstepy wewnatrz)

2018-04-08 22:21 UTC, MaKu-kodilla commented
ajj pomyliło mi się, będę już o tym pamiętał na przyszłość :)

2018-04-09 13:59 UTC, michal-bootcamp commented
chodzilo mi o to, zeby te buttony mialy taka sama wysokosc (odstepy wewnatrz): https://scr.hu/4XJY7G

2018-04-11 19:54 UTC, michal-bootcamp requested changes

2018-04-11 19:54 UTC, michal-bootcamp commented on Zadanie 12.2 Aplikacja losująca cytaty/index.html
> +    </head>
bedzie wygladac dobrze pod mobile jak dodasz meta viewport

2018-04-11 21:18 UTC, merged